### ISSUE TITLE
Salty Finder breaks saltbot

### ISSUE THREAD

**Issue by calexil** [mrmoss/saltybet_tools_chrome_extension#10]
https://github.com/mrmoss/saltybet_tools_chrome_extension/blob/e89753a6781147a9aa03c5ca56efcbb95f297bf7/js/background.js#L63

this line breaks https://github.com/synkarius/saltbot by hiding the Tournament Balance element which the bot needs to function. 

if possible this line should be pulled or reworded

**Comment by mrmoss** [comment]
I remember clearing that our for some reason...doesn't seem to break anything if I leave it in. I'll upload the new chrome extension - may take up to 24 hours to show on the chrome store.

**Comment by calexil** [comment]
thanks Mike

**Comment by calexil** [comment]
https://github.com/mrmoss/saltybet_tools_chrome_extension/commit/84e7abbf4b204ff18dd678c506f4c18c90d1f99b

this commit included it, so it might have re-broken tournament mode

**Comment by mrmoss** [comment]
Tournament mode never worked. This entire project is a blur in my mind :P
