### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by AaroPro** [mrmoss/saltybet_tools_chrome_extension#12]
The site updated, but the updates for the site seem to not be working properly (just says "Link" under the betting buttons).  I think you need to add the /live/ branch.  It's either that or poor host latency on the site causing the issue.

**Comment by mrmoss** [comment]
Weird. Requests coming from the extensions don't seem to be getting a response at all. Although running a request via "copy as curl" from the chrome developer tools network tab works fine.

**Comment by mrmoss** [comment]
So this seems to be failing due to changes in Cross-Origin Read Blocking (CORB) rules in Chrome. The requests are being blocked once they are received. I'll see if I can find a workaround.

**Comment by AaroPro** [comment]
Also, SB(dot)com is currently going through quite a bit of code changes itself, at least what I've noticed over the past couple of weeks.  Not sure of the dependencies, but something to take note.

**Comment by mrmoss** [comment]
I'm uploading the fixed chrome extension to the store now.
Edit 1: I'll keep this open until the store updates.
Edit 2: Note - store updates can take up to an hour. And thanks for letting me know btw! I rarely have the time to use saltybet anymore :P
