### ISSUE TITLE
Broken in tournament mode

### ISSUE THREAD

**Issue by calexil** [mrmoss/saltybet_tools_chrome_extension#3]
elements are not working right in tournament mode:

![screenshot at 2016-12-13 01-57-07](https://cloud.githubusercontent.com/assets/3487071/21130651/0474d882-c0d8-11e6-8e5c-cece432a817c.png)

![screenshot at 2016-12-13 01-57-36](https://cloud.githubusercontent.com/assets/3487071/21130655/09d5e302-c0d8-11e6-9c5c-ba389546d47d.png)

**Comment by mrmoss** [comment]
So I *think* my last push fixed this issue. Hardest part is testing since nothing beats a live test, but if I don't catch it fast I miss the specific game mode. Newest version should show up on the chrome store within the hour (depending on how long they take to update the store).

**Comment by calexil** [comment]
fantastic @mrmoss  this in conjunction [with saltbot](https://github.com/synkarius/saltbot) makes for a pretty awesome setup. 

Thanks for your hard work I truly appreciate it.!!

<3

**Comment by calexil** [comment]
I don't think your commit made it thru on the extension store

**Comment by mrmoss** [comment]
Should be up now.

**Comment by calexil** [comment]
yep we good
