### ISSUE TITLE
Data seems very outdated

### ISSUE THREAD

**Issue by calexil** [mrmoss/saltybet_tools_chrome_extension#4]
If you like I can send you some much more fresh match data to update your databse with.

It seems like yours is behind by at least a month

**Comment by calexil** [comment]
Here is a database current to 03/09/17

[saltyRecordsM--2017-3-9-21.3.txt](https://github.com/mrmoss/saltybet_tools_chrome_extension/files/854380/saltyRecordsM--2017-3-9-21.3.txt)

**Comment by calexil** [comment]
It can be decoded with the saltbot api

https://github.com/synkarius/saltbot

**Comment by mrmoss** [comment]
It looks like the server stopped updating the database 12 days ago. Traced it down to a permissions issue (changed permissions to a lower-privileged user, which didn't have permissions to write to the database). Fixed now.

Data is going to be out of date for a few days, I'll look into integrating the saltbot data (looks really easy to integrate).

**Comment by mrmoss** [comment]
I might forget about this if it's closed.

**Comment by calexil** [comment]
gotcha

**Comment by calexil** [comment]
any update to the db?

**Comment by calexil** [comment]
I can export newer records if you need them

**Comment by Zipoj** [comment]
@calexil I would love a recent db, my data has been wiped with the reinstall of my computer, many month of afking records gone

**Comment by mrmoss** [comment]
@calexil I didn't upload the saltbot database. I haven't been monitoring the server for a while (just letting it run). It seems to be inserting data fine (fights are being put in).

Is the data really that stale? Should I be removing old data? Or maybe nuke the current database and start fresh?

**Comment by calexil** [comment]
upon second review it looks like its a lot better now. closing
