### ISSUE TITLE
Salty Finder has just stopped working

### ISSUE THREAD

**Issue by Twiggyseed** [mrmoss/saltybet_tools_chrome_extension#5]
No W/L ratios, no history of fights between the characters, and no working "links" to recorded history for fighters.

Is this just me? or is everyone having the same problems?

**Comment by mrmoss** [comment]
Working for me, can I get a verification on this?

**Comment by Twiggyseed** [comment]
Well shoot, it's working for me again. Sorry about that.

**Comment by mrmoss** [comment]
No worries, it could have been down before I had a chance to try it. I've
been debating moving the server to a new host (since the one it's on seems
really unreliable).

**Comment by Twiggyseed** [comment]
I think that's what it was. I tried visiting the developer site, "https://salty.manly.parts/live/" and it was down, but I wasn't sure if it was down or always like that since I've never visited it. It's up now
