### ISSUE TITLE
Extension no longer works.. server down?

### ISSUE THREAD

**Issue by calexil** [mrmoss/saltybet_tools_chrome_extension#7]

**Comment by mrmoss** [comment]
I migrated it last night, I must have messed something up. Weird thing is that the site seems to be working fine: https://salty.manly.parts

**Comment by mrmoss** [comment]
So this was my fault. I rewrote the entire server yesterday, and there's literally one line of code I forgot to transfer to the chrome extension to make it work:
```
xhr.setRequestHeader('Content-type','application/json');
```

I uploaded the newest version to the chrome app store, should hopefully be up soon (may take up to an hour though). Version will be 2017.6.1.0.

I'll leave this issue open until I see the update on the store.

**Comment by mrmoss** [comment]
Alright, new version updated on store, verified working, closing.

**Comment by calexil** [comment]
Perfect, Thanks Mike!
